@startuml join
'title
'Attester Join protocol
'end title
autonumber

box "IoT Platform"
participant TPM
participant "EMBRAVE\nAgent" as attester_agent
endbox
participant "Join\nService" as join_service

'== LAK creation ==
TPM<-attester_agent: Request for AK creation
TPM<-TPM: Generate AK

'== Start Join protocol ==
TPM<-attester_agent: Request EK_cert
TPM->attester_agent: EK_cert
attester_agent->join_service: POST /api/request_join: AK pub, AK name, EK cert\n                                      IP address, port, Whitelist URI
note right
The attester notifies its presence.
The join server responds with a challenge.
end note

' alt alredy joined
'  join_service->attester_agent: OK
' else join
  join_service->join_service: Validate EK_cert
  note right
    TPM is authentic
    (validation of the EK certificate OK)
  end note
  join_service->join_service: challenge = TPM2_MakeCredential(EK_pub, nonce, AK_name)
  attester_agent<-join_service: challenge
  TPM<-attester_agent: TPM2_ActivateCredential
  note left
    TPM2_ActivateCredential verifies
    the possession of AK_priv, EK_priv
    and verifies that they are in the
    same TPM
  end note
  TPM<-TPM: activate_credential(EK_priv, challenge)
  TPM->attester_agent: nonce
  attester_agent->join_service: POST /api/confirm_credential: nonce
  join_service->join_service: Store Attester credential in the DB
  join_service->Verifier: Notify a Verifier to start RA on the new Attester
' end

@enduml
