@startuml remote_attestation
title
Remote Attestation protocol
end title

autonumber

box "Platform"
participant TPM
participant "Attester\nAgent" as attester_agent
endbox
participant "Verifier" as verifier
participant "Join Service" as join_service

loop
verifier->attester_agent: Attestation request (PCRs, nonce)
attester_agent->TPM: Load EK
TPM->attester_agent: (EK_handle, EK_pub)
attester_agent->TPM: Load AK
TPM->attester_agent: (AK_handle, AK_pub)
attester_agent->TPM: tpm_quote (PCRs, nonce)
TPM->attester_agent: Quote
attester_agent<-attester_agent: Collect IMA log
attester_agent->verifier: Quote, IMA log
verifier->verifier: Verfiy quote
verifier->verifier: Veryfy IMA log against the whitelist
group if Verification fails
  verifier -> join_service: Notify the failure
  verifier -> verifier: stop RA
else
  verifier -> verifier: continue RA
end
end
join_service -> join_service: Store the failure event
join_service -> join_service:  Notify the event